// Code generated by Axiom CLI; DO NOT EDIT.
//! axiom_context — the single platform-capability surface injected into every
//! node function (ADR-001). A node handler receives `ax: &dyn AxiomContext` and
//! reaches logging, secrets, agent memory, reflection, and mutation through it.

use std::collections::HashMap;

// ── Logging & secrets ───────────────────────────────────────────────────────

/// Structured logger pre-configured for a single node invocation.
pub trait AxiomLogger: Send + Sync {
    fn debug(&self, msg: &str, attrs: &HashMap<&str, String>);
    fn info(&self, msg: &str, attrs: &HashMap<&str, String>);
    fn warn(&self, msg: &str, attrs: &HashMap<&str, String>);
    fn error(&self, msg: &str, attrs: &HashMap<&str, String>);
}

/// Read-only access to tenant secrets resolved by the platform.
pub trait AxiomSecrets: Send + Sync {
    /// Returns `(value, true)` when the named secret is present, else `("", false)`.
    fn get(&self, name: &str) -> (String, bool);
}

// ── Agent memory hierarchy (ADR-002) ────────────────────────────────────────
// Core-first (ADR-056): the trait surface mirrors the Python/Go reference so node
// code compiles against the full hierarchy; the concrete impl is a noop until the
// async tonic memory-proxy client lands (tracked follow-up).

/// A single message in an episodic session history.
#[derive(Clone, Debug, Default)]
pub struct ConversationTurn {
    pub id: String,
    pub session_id: String,
    pub role: String, // "user" | "assistant" | "tool" | "system"
    pub content: String,
    pub tool_name: String,
    pub tool_call_id: String,
    pub created_at: i64, // unix millis
}

/// A semantic or episodic memory retrieved from the memory layer.
#[derive(Clone, Debug, Default)]
pub struct MemoryEntry {
    pub id: String,
    pub scope_level: String,
    pub memory_type: String,
    pub content: String,
    pub importance: f32,
    pub confidence: f32,
    pub score: f32,
    pub created_at: i64,
}

/// Episodic turn-by-turn history for a session.
/// Obtain via `ax.agent().memory().session(id).history()`.
pub trait SessionHistory: Send + Sync {
    /// Most recent `n` turns, oldest-first (for LLM context injection).
    fn last(&self, n: usize) -> Result<Vec<ConversationTurn>, Box<dyn std::error::Error>>;
    /// Append a turn. role: "user" | "assistant" | "tool" | "system".
    fn append(&self, role: &str, content: &str) -> Result<(), Box<dyn std::error::Error>>;
}

/// Semantic memory + history scoped to a single session.
pub trait SessionMemory: Send + Sync {
    fn search(&self, query: &str, limit: usize) -> Result<Vec<MemoryEntry>, Box<dyn std::error::Error>>;
    fn write(&self, content: &str, importance: f32) -> Result<String, Box<dyn std::error::Error>>;
    fn history(&self) -> Box<dyn SessionHistory>;
    fn end(&self) -> Result<(), Box<dyn std::error::Error>>;
}

/// Full memory hierarchy for this flow. Obtain via `ax.agent().memory()`.
pub trait AgentMemory: Send + Sync {
    /// Memory scoped to a specific session id (from the typed input — never inferred).
    fn session(&self, session_id: &str) -> Box<dyn SessionMemory>;
    fn search(&self, query: &str, limit: usize) -> Result<Vec<MemoryEntry>, Box<dyn std::error::Error>>;
    fn write(&self, content: &str, importance: f32) -> Result<String, Box<dyn std::error::Error>>;
}

/// Agent-specific platform capabilities. Obtain via `ax.agent()`.
pub trait Agent: Send + Sync {
    fn memory(&self) -> Box<dyn AgentMemory>;
}

// ── Reflection (ADR-050 / ADR-055) ──────────────────────────────────────────

/// One node placement in the running flow.
#[derive(Clone, Debug, Default)]
pub struct ReflectionNode {
    pub instance_id: u32,
    pub node_ulid: String,
    pub name: String,
    pub package_name: String,
    pub package_version: String,
    pub node_type: String, // "node" | "subflow" | "pipeline"
    pub input_message_name: String,
    pub output_message_name: String,
    pub canvas_node_id: String,
}

/// Agent-readable digest of an edge's dispatch condition (ADR-055 / GAP-4):
/// e.g. field="tools", op="EQ", operands=["ToolX"] means "ToolX" ∈ tools.
#[derive(Clone, Debug, Default)]
pub struct ConditionSummary {
    pub field: String,
    pub op: String,
    pub operands: Vec<String>,
}

/// One edge (forward or loop) in the running flow. `has_condition`/`has_adapter`
/// are structural flags; `condition_summary` is `Some` only when conditional.
#[derive(Clone, Debug, Default)]
pub struct ReflectionEdge {
    pub src_instance: u32,
    pub dst_instance: u32,
    pub canvas_edge_id: String,
    pub has_condition: bool,
    pub has_adapter: bool,
    pub max_iterations: u32,
    pub condition_summary: Option<ConditionSummary>,
}

/// Where the current invocation sits in the running flow.
#[derive(Clone, Debug, Default)]
pub struct FlowPosition {
    pub current_instance: u32,
    pub depth: u32,
    pub loop_iterations: HashMap<u32, u32>,
    pub subflow_stack_graph_ids: Vec<String>,
}

/// Read-only view of the running flow graph + position.
/// Obtain via `ax.reflection().flow()`.
pub trait FlowReflection: Send + Sync {
    fn nodes(&self) -> &[ReflectionNode];
    fn edges(&self) -> &[ReflectionEdge];
    fn loop_edges(&self) -> &[ReflectionEdge];
    fn position(&self) -> &FlowPosition;
    fn graph_id(&self) -> &str;
}

/// Reflection capability bundle. Today exposes only `flow()`.
pub trait Reflection: Send + Sync {
    fn flow(&self) -> &dyn FlowReflection;
}

// ── Mutation (ADR-051 / ADR-054) ────────────────────────────────────────────

/// Optional structural predicate gating a mutation-added edge (ADR-054 / GAP-1).
/// {op:"EQ", field:"tools", value:"ToolX"} expresses "ToolX" in tools.
#[derive(Clone, Debug, Default)]
pub struct EdgeCondition {
    pub op: String,
    pub field: String,
    pub value: String,
}

/// Optional canvas placement hint for an added node.
#[derive(Clone, Copy, Debug, Default)]
pub struct CanvasPosition {
    pub x: f64,
    pub y: f64,
}

/// Append-only mutation surface for the running flow. `add_node` returns the
/// batch-local instance id; use it on subsequent `add_edge` calls.
pub trait FlowMutation: Send + Sync {
    fn add_node(&self, package_name: &str, package_version: &str, canvas_position: Option<CanvasPosition>) -> u32;
    /// Wire src→dst. `Some(condition)` for a conditional dispatch edge (ADR-054);
    /// `None` for an unconditional edge (v1).
    fn add_edge(&self, src_instance: u32, dst_instance: u32, condition: Option<EdgeCondition>);
}

/// Mutation capability bundle. Today exposes only `flow()`.
pub trait Mutation: Send + Sync {
    fn flow(&self) -> &dyn FlowMutation;
}

// ── The injection point ─────────────────────────────────────────────────────

/// AxiomContext — the single platform-capability surface for one invocation.
/// Passed as `ax: &dyn AxiomContext` to every node handler.
pub trait AxiomContext: Send + Sync {
    fn log(&self) -> &dyn AxiomLogger;
    fn secrets(&self) -> &dyn AxiomSecrets;
    fn agent(&self) -> &dyn Agent;
    fn execution_id(&self) -> &str;
    fn flow_id(&self) -> &str;
    fn tenant_id(&self) -> &str;
    /// Flow reflection — `ax.reflection().flow()` (ADR-050).
    fn reflection(&self) -> &dyn Reflection;
    /// Mid-execution mutation — `ax.mutation().flow()` (ADR-051).
    fn mutation(&self) -> &dyn Mutation;
}
